---
title: "Group8_Project"
author: "Misha Aggarwal, Madalina Dumitrescu, Yung-Chieh Hsu, Wendy Li, Christoph Plachutta, Tianyi Zhang"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---

```{r, setup, echo=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```

```{r load-libraries, echo=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(GGally)
library(readxl)
library(here)
library(skimr)
library(janitor)
library(broom)
library(performance)
library(car)
library(lubridate)
```

```{r set_global_theme}

theme_set(theme_bw())

```


# Exploratory Data Analysis

```{r load_data}

# Load data into environment and assign to variables
sales <- vroom::vroom("data/sales.csv")
details <- vroom::vroom("data/details.csv")
stores <- vroom::vroom("data/stores.csv")

```

```{r clean_names}

# Clean names of data frames
sales <- janitor::clean_names(sales)
details <- janitor::clean_names(details)
stores <- janitor::clean_names(stores)

```

```{r inspect_data_sales}

# Inspect Sales data frame
skim(sales)
glimpse(sales)
head(sales)

```
```{r clean_sales_data}

# Change store ID and dept to factor
sales <- sales %>% 
  mutate(store = as.factor(store),
         dept = as.factor(dept),
         # Change date format
         date = dmy(date))

```


```{r inspect_data_details}

# Inspect Sales data frame
skim(details)
glimpse(details)
head(details)

```

```{r clean_details_data}

# Change store ID and dept to factor
details <- details %>% 
  mutate(store = as.factor(store),
         # Change date format
         date = dmy(date),
         mark_down1 = replace_na(mark_down1,0),
         mark_down2 = replace_na(mark_down2,0),
         mark_down3 = replace_na(mark_down3,0),
         mark_down4 = replace_na(mark_down4,0),
         mark_down5 = replace_na(mark_down5,0))

```

```{r inspect_data_stores}

# Inspect Sales data frame
skim(stores)
glimpse(stores)
head(stores)

```

```{r time_span_diff}

# Calculate weeks between min and max date for both data frames
sales %>% 
  summarize(max_date = max(date),
            min_date = min(date),
            weeks_covered = difftime(max_date, min_date, unit = "weeks"))

details %>% 
  summarize(max_date = max(date),
            min_date = min(date),
            weeks_covered = difftime(max_date, min_date, unit = "weeks"))

```

```{r max_departments}

# Calculate weeks between min and max date for both data frames
sales %>% 
  group_by(store) %>% 
  n_distinct(dept) %>% 
  slice_max(n, n = 1)

```

```{r sales_overview_2011}

# Calculate weeks between min and max date for both data frames
sales %>% 
  filter(date >= "2011-01-07" & date <= "2011-12-30") %>% 
  group_by(store) %>% 
  summarize(annl_sales = sum(weekly_sales),
            avg_wkly_sales = annl_sales/difftime("2011-01-07","2011-12-30", unit = "weeks")) %>% 
            arrange(desc(by = annl_sales))

```

```{r join_dataframes}

# Join data frames together and assign to variable
joined_sales <- sales %>% 
  left_join(by = C("store","date"), y = details) %>% 
  left_join(by = "store", y = stores) %>% 
  separate(store,
           into = c("",""),
           sep = "")

sampled_joined <- joined_sales %>% 
  sample_n(1000)

```

```{r distribution_plot_sales}

# Plot distribution of sales
joined_sales %>% 
  ggplot(aes(x = weekly_sales)) +
    geom_density() +
    labs(title = "",
         subtitle = "",
         x = "",
         y = "")

```

```{r spread_plot_sales}

# Plot distribution of sales
joined_sales %>% 
  group_by(store) %>% 
  ggplot(aes(x = weekly_sales) +
         geom_boxplot() +
         facet_grid()

```
# Inferential Statistics

# Regression
